name: diffinv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # safer than 3.13 for PyTorch
  - pip
  - numpy=2.2.5
  - scipy=1.15.2
  - scikit-image=0.25.2
  - matplotlib=3.10.1
  - pillow
  - imageio=2.37.0
  - tifffile=2025.5.10
  - h5py=3.13.0
  - hdf5storage=0.2.0
  - jupyter
  - seaborn  # optional, for plots
  - pip:
      - deepinv @ git+https://github.com/deepinv/deepinv.git@c34e4c19a476640d7d69d90c0b23c8dbd035983c
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - einops==0.8.1
      - lpips==0.1.4
      - wandb==0.19.10
